name: Legacy Link Format Checker

on:
  push:
    paths:
      - "website/docs/**/*.mdx"
      - "website/data/*-nav-data.json"

jobs:
  check-links:
    uses: hashicorp/dev-portal/.github/workflows/docs-content-check-legacy-links-format.yml@5caf6260e0ea2f6a452a0791c7b7f88ebebf12d0
    with:
      repo-owner: "hashicorp"
      repo-name: "terraform-docs-agents"
      commit-sha: ${{ github.sha }}
      mdx-directory: "website/docs"
      nav-data-directory: "website/data"
